version: '{build}-{branch}'

branches:
  except:
    - master

clone_depth: 50


init:
- ps: |
    function craft($target) {
        & C:\Python36\python.exe "C:\CraftMaster\CraftMaster\CraftMaster.py" --config "$env:APPVEYOR_BUILD_FOLDER\.appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $target -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    git submodule update --init --recursive

    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 https://github.com/KDE/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"

    craft $env:TARGET -i craft
    craft $env:TARGET --add-blueprint-repository [git]https://github.com/ecclesias-de/craft-blueprints-ecclesiasdrive.git
    craft $env:TARGET --install-deps ecclesiasdrive

build_script:
- ps: |
    craft $env:TARGET --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER ecclesiasdrive

test_script:
- ps: |
   craft $env:TARGET --src-dir $env:APPVEYOR_BUILD_FOLDER --test ecclesiasdrive

after_test:
- ps: |
    craft $env:TARGET --src-dir $env:APPVEYOR_BUILD_FOLDER --options [Packager]PackageType=NullsoftInstallerPackager --package ecclesiasdrive

artifacts:
  - path: binaries\**\*.exe
    name: ecclesiasdrive_artifact

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: MW3MTcfwOL8T9SbxbqDS4HkOa6aI/ErApmqVVcsWQQqKVPPkBjMtzSWudE8z/hBg # your encrypted token from GitHub
  artifact: ecclesiasdrive_artifact           # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

environment:
    matrix:
    - TARGET: windows-msvc2017_32-cl
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TARGET: windows-msvc2017_64-cl
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
